version: '3.1'
services:
  frontend:
    build: ./frontend
    image: kellraym/crud_app_raykell_frontend
    container_name: frontend
    volumes:
      - /home/kellraym/test/crud-app-raykell/frontend
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - server

  server:
    build: ./backend
    image: kellraym/crud_app_raykell_backend
    container_name: backend
    volumes:
      - /home/kellraym/test/crud-app-raykell/backend
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/crud_app_raykell
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: crud_app_raykell
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge